"""Gotta Evade 'em All - Emily Chaffey - Full Unit 1920 IY4500 """

""" This class takes the reports generated by Cuckoo and transforms it into a csv which only contains the sample name, its score and an assigned x value."""

import json, os, csv
import numpy as np

class scoreScraper():
    def addSig(self,results, name, score):
        newVal = {name: score}
        results.update(newVal)

    def mal(self):
        results = dict()
        results['Malware'] = 'xVal; Score'
        inputdir = "../Reports/MalwareReports/" 
        for file in os.listdir(inputdir):
            data = json.load(open(inputdir+file))
            json_str = json.dumps(data)
            data = json.loads(json_str)
            score = data['info']['score']
            name = data['target']['file']['name']
            self.addSig(results, name, score)
        fileW = open('resultsM.csv', 'w')
        writer = csv.writer(fileW, delimiter =";")
        count=1
        for item in results:
            if not 'Malware' in str(item):
                n = str(item).replace("_","{\_}")
                score = str(results[item]).replace("\"","")
                s = str(count)+";"+score
                val = [n,s]
                count += 1
            else:
                n = str(item).replace("_","{\_}")
                score = str(results[item]).replace("\"","")
                s = score
                val = [n,s]
            writer.writerow(val)
           
    def benign(self):
        results = dict()
        results['Benign'] = 'xVal; Score'
        inputdir = "../Reports/BenignReports/" 
        for file in os.listdir(inputdir):
            data = json.load(open(inputdir+file))
            json_str = json.dumps(data)
            data = json.loads(json_str)
            score = data['info']['score']
            name = data['target']['file']['name']
            self.addSig(results, name, score)
        fileW = open('resultsB.csv', 'w')
        writer = csv.writer(fileW, delimiter =";")
        count = 1
        for item in results:
            if not 'Benign' in str(item):
                n = str(item).replace("_","{\_}")
                score = str(results[item]).replace("\"","")
                s = str(count)+";"+score
                val = [n,s]
                count += 1
            else:
                n = str(item).replace("_","{\_}")
                score = str(results[item]).replace("\"","")
                s = score
                val = [n,s]
            writer.writerow(val)
    
    def __init__(self, malware):
        file_path = os.path.dirname(os.path.abspath(__file__)) #These two lines of code enable the program to know where its file directory sits so that it can load files.
        os.chdir(file_path)
        if malware:
            self.mal()
        else:
            self.benign()